<?php

namespace Kilik\DbMonitorBundle\Repository;

/**
 * DailyHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DailyHistoryRepository extends AbstractHistoryRepository
{
}
