<?php

namespace Kilik\DbMonitorBundle\Repository;

/**
 * HourlyHistoryRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HourlyHistoryRepository extends AbstractHistoryRepository
{
}
