<?php

namespace Kilik\DbMonitorBundle\Repository;

/**
 * MonthlyHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MonthlyHistoryRepository extends \Doctrine\ORM\EntityRepository
{
}
