<?php

namespace Kilik\DbMonitorBundle\Repository;

/**
 * ServerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServerRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Count servers
     *
     * @return int
     */
    public function count()
    {
        $qb=$this->createQueryBuilder('s')->select('count(s) AS nb');
        $row=$qb->getQuery()->getOneOrNullResult();
        return $row['nb'];
    }
}
